---
title: "Reproducible Research: Peer Assessment 1"
output: html_document
---
Basic settings

```{R}
echo = TRUE  # Always make code visible
options(scipen = 1)  # Turn off scientific notations for numbers
```

Loading and processing the data

```{R}
setwd("C:/DataScience/Reproducible Research") # Set the working Directory 
unzip("repdata-data-activity.zip")
data <- read.csv("activity.csv", colClasses = c("integer", "Date", "factor"))
data$month <- as.numeric(format(data$date, "%m"))
noNA <- na.omit(data)
rownames(noNA) <- 1:nrow(noNA)
head(noNA)
```
##What is mean total number of steps taken per day?

For this part of the assignment, you can ignore the missing values in the dataset.

1. Calculate the total number of steps taken per day

```{R}
steps_per_day <- aggregate(steps ~ date , noNA , sum)# Compute the total number of steps each day
colnames(steps_per_day) <- c("date","steps")
head(steps_per_day)
```

2. Make a histogram of the total number of steps taken each day

```{R}
library(ggplot2)
ggplot(noNA, aes(date, steps)) + geom_bar(stat = "identity", colour = "orange", fill = "orange", width = 0.7) + facet_grid(. ~ month, scales = "free") + labs(title = "Histogram of Total Number of Steps Taken Each Day", x = "Date", y = "Total number of steps")
```


3. Calculate and report the mean and median of the total number of steps taken per day

```{R}
totalSteps <- aggregate(noNA$steps, list(Date = noNA$date), FUN = "sum")$x
meanstep <- mean(totalSteps)
medianstep <- median(totalSteps)
```
mean of the total number of steps taken per day = `r meanstep`

median of the total number of steps taken per day = `r medianstep`

##What is the average daily activity pattern?

1. Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)

```{R}
avgSteps <- aggregate(noNA$steps, list(interval = as.numeric(as.character(noNA$interval))), FUN = "mean")
names(avgSteps)[2] <- "meanOfSteps"
ggplot(avgSteps, aes(interval, meanOfSteps)) + geom_line(color = "steelblue", size = 0.8) + labs(title = "Time Series Plot of the 5-minute Interval", x = "5-minute intervals", y = "Average Number of Steps Taken")
```

2. Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

```{R}
avgSteps[avgSteps$meanOfSteps == max(avgSteps$meanOfSteps), ]
```

##Imputing missing values

1. Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)

```{R}
missing_vals <- sum(is.na(data))
```
The total number of missing values are `r missing_vals` .

2. Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.

3. Create a new dataset that is equal to the original dataset but with the missing data filled in.

The  strategy used here is the mean for that 5-minute interval to fill each NA value in the steps column.
```{R}
newData <- data 
for (i in 1:nrow(newData)) {
    if (is.na(newData$steps[i])) {
        newData$steps[i] <- avgSteps[which(newData$interval[i] == avgSteps$interval), ]$meanOfSteps
    }
}

head(newData)
```

4. Make a histogram of the total number of steps taken each day

```{R}
ggplot(newData, aes(date, steps)) + geom_bar(stat = "identity",colour = "orange",fill = "orange", width = 0.7) + facet_grid(. ~ month, scales = "free") + labs(title = "Histogram of Total Number of Steps Taken Each Day (no missing data)", x = "Date", y = "Total number of steps per Day")
```

### Calculate and report the mean and median total number of steps taken per day. 

```{R}
newTotalSteps <- aggregate(newData$steps, 
                           list(Date = newData$date), 
                           FUN = "sum")$x
newMean <- mean(newTotalSteps)
newMedian <- median(newTotalSteps)
```
New mean of the total number of steps taken per day = `r newMean`

New median  of the total number of steps taken per day = `r newMedian`

### Compare them with the two before imputing missing data:

Before filling the data

   - Mean : `r meanstep`  
   - Median: `r medianstep`
  
After filling the data

  - Mean : `r newMean`  
  - Median:`r newMedian`

So, after imputing the missing data, the new mean of total steps taken per day is the same as that of the old mean; the new median of total steps taken per day is greater than that of the old median.

## Are there differences in activity patterns between weekdays and weekends?

1. Create a new factor variable in the dataset with two levels - "weekday" and "weekend" indicating whether a given date is a weekday or weekend day.

```{R}
newData$weekdays <- factor(format(newData$date, "%A"))
levels(newData$weekdays) <- list(weekday = c("Monday", "Tuesday",
                                             "Wednesday", 
                                             "Thursday", "Friday"),
                                 weekend = c("Saturday", "Sunday"))
head(newData)
```

2. Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). See the README file in the GitHub repository to see an example of what this plot should look like using simulated data.

```{R}

avgSteps <- aggregate(newData$steps, 
                      list(interval = as.numeric(as.character(newData$interval)), 
                           weekdays = newData$weekdays),
                      FUN = "mean")
names(avgSteps)[3] <- "meanOfSteps"
library(lattice)
xyplot(avgSteps$meanOfSteps ~ avgSteps$interval | avgSteps$weekdays, 
       layout = c(1, 2), type = "l", 
       xlab = "Interval", ylab = "Number of steps")
```